const products = [
    {
        id: '1_05',
        src_1: '/src/assets/products/1_05_01.avif',
        src_2: '/src/assets/products/1_05_02.avif',
        src_3: '/src/assets/products/1_05_03.avif',
        src_4: '/src/assets/products/1_05_04.avif',
        src_5: '/src/assets/products/1_05_05.avif',
        src_6: '/src/assets/products/1_05_06.avif',
        src_7: '/src/assets/products/1_05_07.avif',
        src_8: '/src/assets/products/1_05_08.avif',
        src_9: '/src/assets/products/1_05_09.avif',
        src_10: '/src/assets/products/1_05_10.avif',
        title: "Нож-подвеска",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, твердость 61 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: сборная петля, кожаный шнур, кожа, покраска, пропитка, финиш.",
        filter: "knives-mini",
        alt: "Мини-нож с рукоятью из дерева неоднородного цвета, клинок грубой формы с выемкой по длине. Ножны из толстой кожи с заклепками.",
        keywords: "Нож-подвеска, мини-нож, сталь у12а, 61 hrc, грубый, карельская берёза, береза, кожаный шнур, кожа, заклепки, деревянная рукоять, дерево, черный, ножны, темный",
    },
    {
        id: '2_01',
        src_1: '/src/assets/products/2_01_01.avif',
        src_2: '/src/assets/products/2_01_02.avif',
        src_3: '/src/assets/products/2_01_03.avif',
        src_4: '/src/assets/products/2_01_04.avif',
        src_5: '/src/assets/products/2_01_05.avif',
        src_6: '/src/assets/products/2_01_06.avif',
        src_7: '/src/assets/products/2_01_07.avif',
        src_8: '/src/assets/products/2_01_08.avif',
        src_9: '/src/assets/products/2_01_09.avif',
        src_10: '/src/assets/products/2_01_10.avif',
        title: "Нож. Финка",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамасская сталь, закалка 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, чёрный граб, бронза.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож с темным клинком из дамасской стали, рукоять черная со вставками из бронзы. Ножны черного цвета.",
        keywords: "Финский нож, финка, дамаск, дамасская сталь, волнистые узоры, 60 hrc, карельская берёза, береза, дерево, деревянная рукоять, черный граб, бронза, кожа, ножны, темный",
    },
    {
        id: '2_02',
        src_1: '/src/assets/products/2_02_01.avif',
        src_2: '/src/assets/products/2_02_02.avif',
        src_3: '/src/assets/products/2_02_03.avif',
        src_4: '/src/assets/products/2_02_04.avif',
        src_5: '/src/assets/products/2_02_05.avif',
        src_6: '/src/assets/products/2_02_06.avif',
        src_7: '/src/assets/products/2_02_07.avif',
        title: "Нож. Сборный",
        subtitle: "Сталь Bohler s390",
        descriptionBlade: "Клинок: сталь Bohler s390, 68 hrc.",
        descriptionHandle: "Рукоять: аризонское железное дерево (Ironwood), больстер титан.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож из стали bohler с рукоятью светло-коричневого цвета с черными полосами, ножны светло-коричневого цвета.",
        keywords: "Нож, сборный, сталь Bohler s390, 68 hrc, аризонское железное дерево (Ironwood), больстер титан, деревянная рукоять, кожа, ножны, светло-коричневый, рыжий, черные полосы",
    },
    {
        id: '2_12',
        src_1: '/src/assets/products/2_12_01.avif',
        src_2: '/src/assets/products/2_12_02.avif',
        src_3: '/src/assets/products/2_12_03.avif',
        src_4: '/src/assets/products/2_12_04.avif',
        src_5: '/src/assets/products/2_12_05.avif',
        src_6: '/src/assets/products/2_12_06.avif',
        src_7: '/src/assets/products/2_12_07.avif',
        src_8: '/src/assets/products/2_12_08.avif',
        src_9: '/src/assets/products/2_12_09.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск, твердость 60 hrc.",
        descriptionHandle: "Рукоять: платан, патинированная бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: разборные на браслет и футляр, кожа, кожа змеи, покраска, пропитка, финиш.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож из дамасской стали, клинок с волнистыми узорами, рукоять коричневого цвета с черными полосками. Ножны разборные.",
        keywords: "Нож, дамаск, дамасская сталь, волнистые узоры, 60 hrc, дерево, деревянная рукоять, платан, патинированная бронза, кожа, ножны разборные, кожа змеи, коричневый, полоски",
    },
    {
        id: '2_03',
        src_1: '/src/assets/products/2_03_01.avif',
        src_2: '/src/assets/products/2_03_02.avif',
        src_3: '/src/assets/products/2_03_03.avif',
        src_4: '/src/assets/products/2_03_04.avif',
        src_5: '/src/assets/products/2_03_05.avif',
        src_6: '/src/assets/products/2_03_06.avif',
        src_7: '/src/assets/products/2_03_07.avif',
        src_8: '/src/assets/products/2_03_08.avif',
        src_9: '/src/assets/products/2_03_09.avif',
        title: "Нож",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, рог лося, бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, рог лося, чёрный граб.",
        filter: "knives-traditional",
        alt: "Нож с темным клинком и черной ручкой, ножны черного цвета со вставкой из рога лося.",
        keywords: "Нож, сталь х12мф, обработка клинка stonewash, 59 hrc, чёрный граб, рог лося, бронза, кожа, ножны, деревянная рукоять, дерево, темный",
    },
    {
        id: '2_09',
        src_1: '/src/assets/products/2_09_01.avif',
        src_2: '/src/assets/products/2_09_02.avif',
        src_3: '/src/assets/products/2_09_03.avif',
        src_4: '/src/assets/products/2_09_04.avif',
        src_5: '/src/assets/products/2_09_05.avif',
        src_6: '/src/assets/products/2_09_06.avif',
        src_7: '/src/assets/products/2_09_07.avif',
        title: "Нож. Трудоголик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: граб, чёрный граб, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с клинком темного цвета, рукоять коричневая с черной вставкой. Ножны черно-коричневые.",
        keywords: "Нож, сталь х12мф, обработка клинка stonewash, 59 hrc, граб, чёрный граб, бронза, дерево, деревянная рукоять, кожа, ножны, темный клинок, черный, ореховый, коричневый",
    },
    {
        id: '2_06',
        src_1: '/src/assets/products/2_06_01.avif',
        src_2: '/src/assets/products/2_06_02.avif',
        src_3: '/src/assets/products/2_06_03.avif',
        src_4: '/src/assets/products/2_06_04.avif',
        src_5: '/src/assets/products/2_06_05.avif',
        src_6: '/src/assets/products/2_06_06.avif',
        src_7: '/src/assets/products/2_06_07.avif',
        src_8: '/src/assets/products/2_06_08.avif',
        src_9: '/src/assets/products/2_06_09.avif',
        src_10: '/src/assets/products/2_06_10.avif',
        title: "Нож. Финка",
        subtitle: "Cталь У8",
        descriptionBlade: "Клинок: сталь У8, воронение, закалка 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, фибра, бронза.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с клинком темного цвета и светло-зеленой неоднородной рукоятью с бежевой вставкой, ножны светло-коричневого цвета.",
        keywords: "Финский нож, финка, сталь У8, воронение, 60 hrc, карельская берёза, бронза, дерево, деревянная рукоять, кожа, ножны, зеленый, бежевый, коричневый, шнурок, темный клинок, черный",
    },
    {
        id: '4_06',
        src_1: '/src/assets/products/4_06_03.avif',
        src_2: '/src/assets/products/4_06_04.avif',
        src_3: '/src/assets/products/4_06_05.avif',
        src_4: '/src/assets/products/4_06_06.avif',
        src_5: '/src/assets/products/4_06_01.avif',
        src_6: '/src/assets/products/4_06_02.avif',
        title: "Топор",
        subtitle: "Сталь ст45, 60с2а",
        descriptionBlade: "Топор: тело ст45, вваренное лезвие 60с2а, твердость 56 hrc.",
        descriptionHandle: "Топорище: бук, пропитка.",
        descriptionScabbard: "Чехол: тиснение, покраска, пропитка восками.",
        filter: "axes",
        alt: "Топор.",
        keywords: "Топор, тело сталь ст45, вваренное лезвие 60с2а, 56 hrc, топорище, бук, дерево, деревянная рукоять, кожа, чехол, коричневый, фоновое",
    },
    {
        id: '6_02',
        src_1: '/src/assets/products/6_02_01.avif',
        src_2: '/src/assets/products/6_02_02.avif',
        src_3: '/src/assets/products/6_02_03.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, вставка шкура змеи, покраска, пропитка, финиш.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью желто-бежевого неоднородного цвета, ножны светло-коричневые со вставкой из змеиной шкуры зеленого цвета.",
        keywords: "Нож, сталь шх15, 60 hrc, карельская берёза с эффектом изменения цвета, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, вставка шкура змеи, желтый, коричневый, зеленый, чешуя",
    },
    {
        id: '4_01',
        src_1: '/src/assets/products/4_01_01.avif',
        src_2: '/src/assets/products/4_01_02.avif',
        src_3: '/src/assets/products/4_01_03.avif',
        src_4: '/src/assets/products/4_01_04.avif',
        src_5: '/src/assets/products/4_01_05.avif',
        src_6: '/src/assets/products/4_01_06.avif',
        src_7: '/src/assets/products/4_01_07.avif',
        src_8: '/src/assets/products/4_01_08.avif',
        src_9: '/src/assets/products/4_01_09.avif',
        src_10: '/src/assets/products/4_01_10.avif',
        title: "Топорик",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 55 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, амарант, фибра, пропитка.",
        descriptionScabbard: "Чехол: кожа, покраска, пропитка.",
        filter: "other",
        alt: "Топорик кухонный с клинком темного цвета, грубой формы, рукоять бежево-красного цвета со вставкой из красного дерева.",
        keywords: "Топорик кухонный, сталь 60с2а, 55 hrc, карельская берёза, амарант, дерево, деревянная рукоять, кожа, чехол, бежевый, красный, коричневый, темно-бордовый, грубый",
    },
    // ----------------------------------------------------------------------------
    {
        id: '1_02',
        src_1: '/src/assets/products/1_02_01.avif',
        src_2: '/src/assets/products/1_02_02.avif',
        title: "Ножи-подвески",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, закалка 61 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
        alt: "Мини-клинки без рукоятей, на каждом по 3 круглых отверстия. На ножнах тиснения в виде чешуйчатых узоров и в виде солнца.",
        keywords: "Мини-клинок, нож-подвеска, сталь у12а, 61 hrc, кожа, ножны, узор, шнурок, коричневый, солнце, темный клинок",
    },
    {
        id: '2_07',
        src_1: '/src/assets/products/2_07_01.avif',
        src_2: '/src/assets/products/2_07_02.avif',
        src_3: '/src/assets/products/2_07_03.avif',
        src_4: '/src/assets/products/2_07_04.avif',
        src_5: '/src/assets/products/2_07_05.avif',
        src_6: '/src/assets/products/2_07_06.avif',
        src_7: '/src/assets/products/2_07_07.avif',
        title: "Нож. Лёлик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, падук, бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с клинком темного цвета, рукоять светло-коричневая с темно-ореховой вставкой. Ножны светло-коричневые.",
        keywords: "Нож, сталь х12мф, обработка клинка stonewash, 59 hrc, карельская берёза, падук, бронза, дерево, деревянная рукоять, кожа, ножны, светло-коричневый, бежевый, темный клинок, черный",
    },
    {
        id: '2_08',
        src_1: '/src/assets/products/2_08_01.avif',
        src_2: '/src/assets/products/2_08_02.avif',
        src_3: '/src/assets/products/2_08_03.avif',
        src_4: '/src/assets/products/2_08_04.avif',
        src_5: '/src/assets/products/2_08_05.avif',
        title: "Нож. Болик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, микарта, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с клинком темного цвета, рукоять светло-бежевая с черной вставкой. Ножны коричневые.",
        keywords: "Нож, сталь х12мф, обработка клинка stonewash, 59 hrc, карельская берёза, микарта, бронза, дерево, деревянная рукоять, кожа, ножны, темный клинок, светло-бежевый, черный, коричневый",
    },
    {
        id: '1_04',
        src_1: '/src/assets/products/1_04_01.avif',
        src_2: '/src/assets/products/1_04_02.avif',
        src_3: '/src/assets/products/1_04_03.avif',
        src_4: '/src/assets/products/1_04_04.avif',
        src_5: '/src/assets/products/1_04_05.avif',
        title: "Нож-подвеска",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, твердость 61 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, поставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-mini",
        alt: "Мини-нож с рукоятью из дерева неоднородного цвета. На ножнах тиснение в виде чешуйчатого узора.",
        keywords: "Нож-подвеска, мини-нож, сталь у12а, 61 hrc, карельская берёза, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, узор, шнурок, коричневый, рыжий, темный клинок",
    },
    {
        id: '4_03',
        src_1: '/src/assets/products/4_03_01.avif',
        src_2: '/src/assets/products/4_03_02.avif',
        src_3: '/src/assets/products/4_03_03.avif',
        src_4: '/src/assets/products/4_03_04.avif',
        src_5: '/src/assets/products/4_03_05.avif',
        src_6: '/src/assets/products/4_03_06.avif',
        src_7: '/src/assets/products/4_03_07.avif',
        src_8: '/src/assets/products/4_03_08.avif',
        title: "Топорик",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 55 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, орех, фибра, пропитка.",
        descriptionScabbard: "Чехол: кожа, покраска, пропитка.",
        filter: "other",
        alt: "Топорик кухонный с клинком неоднородного цвета, грубой формы, рукоять коричневого цвета с бежевой вставкой.",
        keywords: "Топорик кухонный, сталь 60с2а, 55 hrc, карельская берёза, орех, дерево, деревянная рукоять, кожа, чехол, бежевый, коричневый, полосы, грубый",
    },
    {
        id: '2_10',
        src_1: '/src/assets/products/2_10_01.avif',
        src_2: '/src/assets/products/2_10_02.avif',
        src_3: '/src/assets/products/2_10_03.avif',
        src_4: '/src/assets/products/2_10_04.avif',
        src_5: '/src/assets/products/2_10_05.avif',
        src_6: '/src/assets/products/2_10_06.avif',
        title: "Нож. Крыска",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, карельская берёза, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с клинком темного цвета, рукоять черная со светло-бежевой вставкой. Ножны коричневые.",
        keywords: "Нож, сталь х12мф, обработка клинка stonewash, 59 hrc, чёрный граб, карельская берёза, бронза, кожа, ножны, темный клинок, бордовый, светло-коричневый",
    },
    {
        id: '2_04',
        src_1: '/src/assets/products/2_04_01.avif',
        src_2: '/src/assets/products/2_04_02.avif',
        src_3: '/src/assets/products/2_04_03.avif',
        src_4: '/src/assets/products/2_04_04.avif',
        src_5: '/src/assets/products/2_04_05.avif',
        src_6: '/src/assets/products/2_04_06.avif',
        src_7: '/src/assets/products/2_04_07.avif',
        src_8: '/src/assets/products/2_04_08.avif',
        src_9: '/src/assets/products/2_04_09.avif',
        title: "Нож",
        subtitle: "Cталь 5160 (США)",
        descriptionBlade: "Клинок: сталь 5160 (США), закалка 57 hrc.",
        descriptionHandle: "Рукоять: дуб, дюралюминий, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож со светло-коричневой неоднородной рукоятью, ножны темно-бордового цвета.",
        keywords: "Нож, сталь 5160 (США), 57 hrc, дерево, деревянная рукоять, дуб, дюралюминий, кожа, ножны, светло-коричневый, темно-бордовый",
    },
    {
        id: '2_05',
        src_1: '/src/assets/products/2_05_03.avif',
        src_2: '/src/assets/products/2_05_02.avif',
        src_3: '/src/assets/products/2_05_01.avif',
        src_4: '/src/assets/products/2_05_04.avif',
        src_5: '/src/assets/products/2_05_05.avif',
        src_6: '/src/assets/products/2_05_06.avif',
        src_7: '/src/assets/products/2_05_07.avif',
        src_8: '/src/assets/products/2_05_08.avif',
        title: "Нож",
        subtitle: "Cталь 5160 (США)",
        descriptionBlade: "Клинок: сталь 5160 (США), закалка 57 hrc.",
        descriptionHandle: "Рукоять: дуб, мамонт, титан, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью бежевого цвета с желтизной, больстер в виде черно-белой вставки. Ножны коричневые.",
        keywords: "Нож, сталь 5160 (США), 57 hrc, дерево, деревянная рукоять, дуб, мамонт, титан, ножны, кожа, светло-коричневый",
    },
    {
        id: '1_03',
        src_1: '/src/assets/products/1_03_01.avif',
        src_2: '/src/assets/products/1_03_02.avif',
        src_3: '/src/assets/products/1_03_03.avif',
        src_4: '/src/assets/products/1_03_04.avif',
        src_5: '/src/assets/products/1_03_05.avif',
        src_6: '/src/assets/products/1_03_06.avif',
        src_7: '/src/assets/products/1_03_07.avif',
        src_8: '/src/assets/products/1_03_08.avif',
        title: "Нож-подвеска Птичка",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 56 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
        alt: "Мини-клинок без рукояти, на конце имитация птичьей головы - клюв и глаз. На ножнах тиснение в виде пера.",
        keywords: "Мини-клинок, мини-нож, птичка, сталь 60с2а, 56 hrc, кожа, ножны, перо, коричневый, шнурок, темный клинок",
    },
    {
        id: '2_11',
        src_1: '/src/assets/products/2_11_03.avif',
        src_2: '/src/assets/products/2_11_01.avif',
        src_3: '/src/assets/products/2_11_02.avif',
        src_4: '/src/assets/products/2_11_04.avif',
        src_5: '/src/assets/products/2_11_05.avif',
        src_6: '/src/assets/products/2_11_06.avif',
        src_7: '/src/assets/products/2_11_07.avif',
        src_8: '/src/assets/products/2_11_08.avif',
        src_9: '/src/assets/products/2_11_09.avif',
        src_10: '/src/assets/products/2_11_10.avif',
        title: "Нож. Совелий",
        subtitle: "Cталь У12",
        descriptionBlade: "Клинок: сталь У12, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, литьё мельхиор, проставки фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional",
        alt: "Нож с темной рукояткой неоднородного цвета, на навершии голова филина.",
        keywords: "Нож, сталь У12, зонная закалка, 58 hrc, карельская берёза, литьё мельхиор, дерево, деревянная рукоять, кожа, ножны, филин, сова, символы",
    },
    // ------------------------------------------------------------------------
    {
        id: '3_06',
        src_1: '/src/assets/products/3_06_01.avif',
        src_2: '/src/assets/products/3_06_02.avif',
        src_3: '/src/assets/products/3_06_03.avif',
        src_4: '/src/assets/products/3_06_04.avif',
        src_5: '/src/assets/products/3_06_05.avif',
        src_6: '/src/assets/products/3_06_06.avif',
        src_7: '/src/assets/products/3_06_07.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, твердость 57 hrc.",
        descriptionHandle: "Рукоять: падук, кавказский орех, поставка фибра, пропитка.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
        alt: "Шеф-нож с рукоятью из красного дерева с ореховой вставкой.",
        keywords: "Шеф-нож, кухонный нож, сталь 95х18, 57 hrc, падук, кавказский орех, дерево, деревянная рукоять, красный, бордовый, бежевый",
    },
    {
        id: '4_02',
        src_1: '/src/assets/products/4_02_01.avif',
        src_2: '/src/assets/products/4_02_02.avif',
        title: "Ножи метательные",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 54 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
        alt: "Метательные ножи.",
        keywords: "Метательные ножи, сталь 60с2а, 54 hrc",
    },
    {
        id: '3_04',
        src_1: '/src/assets/products/3_04_01.avif',
        src_2: '/src/assets/products/3_04_02.avif',
        src_3: '/src/assets/products/3_04_03.avif',
        src_4: '/src/assets/products/3_04_04.avif',
        src_5: '/src/assets/products/3_04_05.avif',
        src_6: '/src/assets/products/3_04_06.avif',
        src_7: '/src/assets/products/3_04_07.avif',
        src_8: '/src/assets/products/3_04_08.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, твердость 57 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, амарант, фибра, пропитка.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
        alt: "Шеф-нож с рукоятью бежевого цвета с вкраплениями красного и темно-зеленого, со вставкой из красного дерева.",
        keywords: "Шеф-нож, кухонный нож, сталь 95х18, 57 hrc, карельская берёза, амарант, дерево, деревянная рукоять, красный, бордовый, бежевый, темный",
    },
    {
        id: '4_05',
        src_1: '/src/assets/products/4_05_01.avif',
        src_2: '/src/assets/products/4_05_02.avif',
        src_3: '/src/assets/products/4_05_03.avif',
        src_4: '/src/assets/products/4_05_04.avif',
        title: "Топорик (брелок)",
        subtitle: "Сталь ст3",
        descriptionBlade: "Топор: сталь ст3.",
        descriptionHandle: "Топорище: бук",
        descriptionScabbard: "",
        filter: "other",
        alt: "Топорики небольшого размера.",
        keywords: "Топорики, мини-топор, сталь ст3, бук, дерево, деревянная рукоять",
    },
    {
        id: '3_03',
        src_1: '/src/assets/products/3_03_01.avif',
        src_2: '/src/assets/products/3_03_02.avif',
        src_3: '/src/assets/products/3_03_03.avif',
        src_4: '/src/assets/products/3_03_04.avif',
        src_5: '/src/assets/products/3_03_05.avif',
        src_6: '/src/assets/products/3_03_06.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, закалка 57 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
        alt: "Шеф-нож и нож-универсал, с черными рукоятями.",
        keywords: "Шеф-нож, нож-универсал, кухонный нож, сталь 95х18, 57 hrc, чёрный граб, латунь, дерево, деревянная рукоять",
    },
    {
        id: '6_03',
        src_1: '/src/assets/products/6_03_01.avif',
        src_2: '/src/assets/products/6_03_02.avif',
        src_3: '/src/assets/products/6_03_03.avif',
        src_4: '/src/assets/products/6_03_04.avif',
        src_5: '/src/assets/products/6_03_05.avif',
        src_6: '/src/assets/products/6_03_06.avif',
        src_7: '/src/assets/products/6_03_07.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск ,твердость 61 hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож из дамасской стали, светло-зеленая рукоять. Ножны коричнево-красные, с зеленым тиснением в виде листьев.",
        keywords: "Нож, дамасская сталь, дамаск, 61 hrc, карельская берёза с эффектом изменения цвета, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, волнистые узоры, листья, зеленый, красно-коричневый",
    },
    {
        id: '6_04',
        src_1: '/src/assets/products/6_04_01.avif',
        src_2: '/src/assets/products/6_04_02.avif',
        src_3: '/src/assets/products/6_04_03.avif',
        src_4: '/src/assets/products/6_04_04.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, твердость 59 hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью синего неоднородного цвета. Ножны синего цвета с тиснением в виде волн.",
        keywords: "Нож, сталь шх15, зонная закалка, 59 hrc, карельская берёза с эффектом изменения цвета, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, синий, волны",
    },
    {
        id: '1_01',
        src_1: '/src/assets/products/1_01_01.avif',
        src_2: '/src/assets/products/1_01_02.avif',
        title: "Нож-подвеска Шебутной",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
        alt: "Мини-клинок без рукояти, на конце круглое отверстие. Ножны темно-коричневого цвета с тиснением в виде кота.",
        keywords: "Мини-клинок, мини-нож, нож-подвеска, сталь х12мф, обработка клинка stonewash, 59 hrc, кожа, ножны, котик, коричневый",
    },
    {
        id: '7_05',
        src_1: '/src/assets/products/7_05_09.avif',
        src_2: '/src/assets/products/7_05_01.avif',
        src_3: '/src/assets/products/7_05_02.avif',
        src_4: '/src/assets/products/7_05_03.avif',
        src_5: '/src/assets/products/7_05_04.avif',
        src_6: '/src/assets/products/7_05_05.avif',
        src_7: '/src/assets/products/7_05_06.avif',
        src_8: '/src/assets/products/7_05_07.avif',
        src_9: '/src/assets/products/7_05_08.avif',
        title: "Топор",
        subtitle: "Сталь ст45, 60с2а",
        descriptionBlade: "Тело: сталь ст45, вваренное лезвие 60с2а, твердость 57 hrc.",
        descriptionHandle: "Топорище: бук, нарезка, пропитка.",
        descriptionScabbard: "Чехол: тиснение, покраска, пропитка.",
        filter: "axes",
        alt: "Топор с чехлом. На чехле тиснение в виде дубового листа.",
        keywords: "Топор, сталь ст45, вваренное лезвие 60с2а, 57 hrc, топорище, бук, резьба, дерево, деревянная рукоять, кожа, чехол, дубовый лист, коричневый",
    },
    {
        id: '7_02',
        src_1: '/src/assets/products/7_02_01.avif',
        src_2: '/src/assets/products/7_02_02.avif',
        src_3: '/src/assets/products/7_02_03.avif',
        src_4: '/src/assets/products/7_02_04.avif',
        src_5: '/src/assets/products/7_02_05.avif',
        src_6: '/src/assets/products/7_02_06.avif',
        src_7: '/src/assets/products/7_02_07.avif',
        src_8: '/src/assets/products/7_02_08.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: мербау, чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        descriptionBelt: "Ремень: тиснение, пропитка, покраска. Размер 1200мм на 48мм. Пряжка: торцовый мозаичный дамаск, воронение.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью коричневого цвета, с темной вставкой. Ножны с узорчатым тиснением, разборные.",
        keywords: "Нож, сталь х12мф, узор, 61 hrc, мербау, чёрный граб, патинированная бронза, дерево, деревянная рукоять, кожа, ножны разборные, резьба, ремень, пряжка, узоры, коричневый",
    },
    // ------------------------------------------------------------------------
    {
        id: '7_10',
        src_1: '/src/assets/products/7_10_01.avif',
        src_2: '/src/assets/products/7_10_02.avif',
        src_3: '/src/assets/products/7_10_03.avif',
        src_4: '/src/assets/products/7_10_04.avif',
        src_5: '/src/assets/products/7_10_05.avif',
        src_6: '/src/assets/products/7_10_06.avif',
        title: "Топор",
        subtitle: "Сталь ст45",
        descriptionBlade: "Тело: сталь ст45, вваренное лезвие 60с2а, твердость 57 hrc.",
        descriptionHandle: "Топорище: бук, нарезка, пропитка.",
        descriptionScabbard: "",
        filter: "axes",
        alt: "Топор с черным чехлом.",
        keywords: "Топор, сталь ст45, вваренное лезвие 60с2а, 57 hrc, топорище, бук, дерево, деревянная рукоять, чехол, кожа, черный, коричневый, резьба, шнурок, заклепки",
    },
    {
        id: '3_05',
        src_1: '/src/assets/products/3_05_01.avif',
        src_2: '/src/assets/products/3_05_02.avif',
        src_3: '/src/assets/products/3_05_03.avif',
        src_4: '/src/assets/products/3_05_04.avif',
        src_5: '/src/assets/products/3_05_05.avif',
        src_6: '/src/assets/products/3_05_06.avif',
        src_7: '/src/assets/products/3_05_07.avif',
        src_8: '/src/assets/products/3_05_08.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 440с",
        descriptionBlade: "Клинок: сталь 440с, твердость 57 hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, штифты - нержавеющая сталь, фибра.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-kitchen",
        alt: "Шеф-нож с рукоятью от светло-зеленого до темно-зеленого цвета, ножны темно-зеленого цвета.",
        keywords: "Шеф-нож, кухонный нож, сталь 440с, 57 hrc, стабилизированная карельская берёза, штифты - нержавеющая сталь, дерево, деревянная рукоять, кожа, ножны, светло-зеленый, темно-зеленый",
    },
    {
        id: '3_02',
        src_1: '/src/assets/products/3_02_01.avif',
        src_2: '/src/assets/products/3_02_02.avif',
        src_3: '/src/assets/products/3_02_03.avif',
        src_4: '/src/assets/products/3_02_04.avif',
        src_5: '/src/assets/products/3_02_05.avif',
        src_6: '/src/assets/products/3_02_06.avif',
        src_7: '/src/assets/products/3_02_07.avif',
        src_8: '/src/assets/products/3_02_08.avif',
        src_9: '/src/assets/products/3_02_09.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 440с",
        descriptionBlade: "Клинок: сталь 440с, закалка 56 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, амарант, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
        alt: "Кухонный нож с рукоятью светло-бежевого цвета вперемешку с черными полосами и вкраплениями и со вставкой из красного дерева.",
        keywords: "Кухонный нож, нож-универсал, сталь 440с, 56 hrc, карельская берёза, амарант, дерево, деревянная рукоять, темно-бордовый, бежевый, красный",
    },
    {
        id: '7_01',
        src_1: '/src/assets/products/7_01_01.avif',
        src_2: '/src/assets/products/7_01_02.avif',
        src_3: '/src/assets/products/7_01_03.avif',
        src_4: '/src/assets/products/7_01_04.avif',
        src_5: '/src/assets/products/7_01_05.avif',
        src_6: '/src/assets/products/7_01_06.avif',
        title: "Нож. Финка",
        subtitle: "Сталь 50хфа",
        descriptionBlade: "Клинок: сталь 50хфа, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью темного цвета, с двумя красными полосками, навершие из бронзы. Ножны с узорчатым тиснением, разборные.",
        keywords: "Финский нож, финка, сталь 50хфа, зонная закалка, 58 hrc, чёрный граб, патинированная бронза, дерево, деревянная рукоять, кожа, ножны разборные, черный, красный, коричневый, узоры",
    },
    {
        id: '7_03',
        src_1: '/src/assets/products/7_03_01.avif',
        src_2: '/src/assets/products/7_03_02.avif',
        src_3: '/src/assets/products/7_03_03.avif',
        src_4: '/src/assets/products/7_03_04.avif',
        src_5: '/src/assets/products/7_03_05.avif',
        src_6: '/src/assets/products/7_03_06.avif',
        src_7: '/src/assets/products/7_03_07.avif',
        src_8: '/src/assets/products/7_03_08.avif',
        src_9: '/src/assets/products/7_03_09.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: покраска, пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Длинный нож с рукоятью темно-коричневого неоднородного цвета. Ножны красноватые, с зеленым узорчатым тиснением.",
        keywords: "Нож, сталь У8, зонная закалка, хамон, 60 hrc, карельская берёза, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, узоры, коричневый, рыжий, зеленый",
    },
    {
        id: '7_04',
        src_1: '/src/assets/products/7_04_01.avif',
        src_2: '/src/assets/products/7_04_02.avif',
        src_3: '/src/assets/products/7_04_03.avif',
        src_4: '/src/assets/products/7_04_04.avif',
        src_5: '/src/assets/products/7_04_05.avif',
        src_6: '/src/assets/products/7_04_06.avif',
        src_7: '/src/assets/products/7_04_07.avif',
        src_8: '/src/assets/products/7_04_08.avif',
        src_9: '/src/assets/products/7_04_09.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, проставка, пропитка.",
        descriptionScabbard: "Ножны: липовый вкладыш, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью бежевого цвета с вкраплениями, ножны с цветом, идущим от черного к красному.",
        keywords: "Нож, сталь У8, зонная закалка, хамон, 60 hrc, карельская берёза, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, липовый вкладыш, бежевый, коричневый, темно-красный",
    },
    {
        id: '8_01',
        src_1: '/src/assets/products/8_01_01.avif',
        src_2: '/src/assets/products/8_01_02.avif',
        src_3: '/src/assets/products/8_01_03.avif',
        src_4: '/src/assets/products/8_01_04.avif',
        src_5: '/src/assets/products/8_01_05.avif',
        src_6: '/src/assets/products/8_01_06.avif',
        src_7: '/src/assets/products/8_01_07.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: амарант, литьё (Сталин), мельхиор, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение,покраска,пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью из красного дерева, на навершии лицо Сталина. Ножны с тиснением в виде звезды, внутри которой серп и молот.",
        keywords: "Нож, сталь х12мф, булатный узор, 61 hrc, амарант, литьё (Сталин), мельхиор, дерево, деревянная рукоять, кожа, ножны, звезда, серп и молот, красный, коричневый, СССР",
    },
    {
        id: '3_01',
        src_1: '/src/assets/products/3_01_01.avif',
        src_2: '/src/assets/products/3_01_02.avif',
        src_3: '/src/assets/products/3_01_03.avif',
        src_4: '/src/assets/products/3_01_04.avif',
        src_5: '/src/assets/products/3_01_05.avif',
        src_6: '/src/assets/products/3_01_06.avif',
        src_7: '/src/assets/products/3_01_07.avif',
        src_8: '/src/assets/products/3_01_08.avif',
        src_9: '/src/assets/products/3_01_09.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, закалка 56 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, амарант, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
        alt: "Шеф-нож и 2 кухонных ножа поменьше с одинаковыми рукоятями неоднородного красного цвета со вставкой из красного дерева.",
        keywords: "Шеф-нож, кухонный нож, нож-универсал, сталь 95х18, 56 hrc, карельская берёза, амарант, дерево, деревянная рукоять, красный, темно-бордовый, коричневый",
    },
    {
        id: '7_06',
        src_1: '/src/assets/products/7_06_01.avif',
        src_2: '/src/assets/products/7_06_02.avif',
        src_3: '/src/assets/products/7_06_03.avif',
        src_4: '/src/assets/products/7_06_04.avif',
        src_5: '/src/assets/products/7_06_05.avif',
        src_6: '/src/assets/products/7_06_06.avif',
        src_7: '/src/assets/products/7_06_07.avif',
        src_8: '/src/assets/products/7_06_08.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, булатный узор, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с коричнево-черной рукоятью, ножны черно-красного цвета с оригинальным тиснением.",
        keywords: "Нож, сталь У8, зонная закалка, хамон, булатный узор, 60 hrc, карельская берёза, бронза, дерево, деревянная рукоять, кожа, ножны, узоры, черный, красный, коричневый",
    },
    {
        id: '7_07',
        src_1: '/src/assets/products/7_07_01.avif',
        src_2: '/src/assets/products/7_07_02.avif',
        src_3: '/src/assets/products/7_07_03.avif',
        src_4: '/src/assets/products/7_07_04.avif',
        title: "Нож. Финка",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с черной рукоятью с двумя красными полосками, с золотой вставкой на навершии. Ножны коричневые с крупными заклепками.",
        keywords: "Финский нож, финка, сталь У8, зонная закалка, 58 hrc, чёрный граб, бронза, дерево, деревянная рукоять, кожа, ножны, заклепки, коричневый, золотой",
    },
    // ------------------------------------------------------------------------
    {
        id: '9_01',
        src_1: '/src/assets/products/9_01_01.avif',
        src_2: '/src/assets/products/9_01_02.avif',
        src_3: '/src/assets/products/9_01_03.avif',
        title: "Топор",
        subtitle: "Сталь ст3, 60с2а",
        descriptionBlade: "Тело: сталь ст3, вваренное лезвие 60с2а, твердость 56 hrc.",
        descriptionHandle: "Древко: бук, 105см",
        descriptionScabbard: "",
        filter: "axes",
        alt: "Топор.",
        keywords: "Топор, сталь ст3, вваренное лезвие 60с2а, 56 hrc, древко бук, дерево, деревянная рукоять, черный, светло-коричневый",
    },
    {
        id: '9_02',
        src_1: '/src/assets/products/9_02_01.avif',
        src_2: '/src/assets/products/9_02_02.avif',
        title: "Меч",
        subtitle: "Сталь 60с2",
        descriptionBlade: "Клинок: сталь 60с2, твердость 52 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
        alt: "Меч.",
        keywords: "Меч, сталь 60с2, 52 hrc",
    },
    {
        id: '9_06',
        src_1: '/src/assets/products/9_06_01.avif',
        src_2: '/src/assets/products/9_06_02.avif',
        src_3: '/src/assets/products/9_06_03.avif',
        src_4: '/src/assets/products/9_06_04.avif',
        title: "Тантоноид",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 59 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
        alt: "Тантоноид, скрытый в буковой палке.",
        keywords: "Тантоноид, сталь шх15, зонная закалка, хамон, булатный узор, 59 hrc, бук, дерево, светло-коричневый",
    },
    {
        id: '9_03',
        src_1: '/src/assets/products/9_03_01.avif',
        src_2: '/src/assets/products/9_03_02.avif',
        src_3: '/src/assets/products/9_03_03.avif',
        src_4: '/src/assets/products/9_03_04.avif',
        src_5: '/src/assets/products/9_03_05.avif',
        src_6: '/src/assets/products/9_03_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: клён, резьба Владимира Калуцких",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Нож с оригинальной рукоятью, на которой вырезаны абстрактные узоры, переходящие в голову кота на навершии.",
        keywords: "Нож, сталь шх15, зонная закалка, хамон, булатный узор, 61 hrc, клён, резьба Владимира Калуцких, дерево, деревянная рукоять, абстрактные узоры, голова кота, кожа, ножны, коричневый, шнурок",
    },
    {
        id: '8_02',
        src_1: '/src/assets/products/8_02_01.avif',
        src_2: '/src/assets/products/8_02_02.avif',
        src_3: '/src/assets/products/8_02_03.avif',
        src_4: '/src/assets/products/8_02_04.avif',
        src_5: '/src/assets/products/8_02_05.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, латунь, патинирование, проставка орех, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож рыбацкий, рукоять неоднородного цвета с темно-коричневой вставкой. Ножны с тиснением в виде чешуи.",
        keywords: "Нож рыбацкий, сталь х12мф, булатный узор, 61 hrc, карельская берёза, бронза, латунь, патинирование, проставка орех, дерево, деревянная рукоять, кожа, ножны, чешуя, узор, шнурок, коричневый, ореховый",
    },
    {
        id: '8_03',
        src_1: '/src/assets/products/8_03_01.avif',
        src_2: '/src/assets/products/8_03_02.avif',
        src_3: '/src/assets/products/8_03_03.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамасская сталь у8+шх15, твердость 56 hrc.",
        descriptionHandle: "Рукоять: падук, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож из дамасской стали, рукоять из красного дерева. Ножны с узорчатым тиснением.",
        keywords: "Нож, дамасская сталь, дамаск, сталь у8+шх15, 56 hrc, падук, бронза, дерево, деревянная рукоять, кожа, ножны, волнистые узоры, красный, коричневый",
    },
    {
        id: '8_09',
        src_1: '/src/assets/products/8_09_01.avif',
        src_2: '/src/assets/products/8_09_02.avif',
        src_3: '/src/assets/products/8_09_03.avif',
        src_4: '/src/assets/products/8_09_04.avif',
        src_5: '/src/assets/products/8_09_05.avif',
        src_6: '/src/assets/products/8_09_06.avif',
        src_7: '/src/assets/products/8_09_07.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 62 hrc.",
        descriptionHandle: "Рукоять: корень ореха, бронза, мельхиор.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью коричневого цвета с золотистыми вставками. Ножны темно-коричневые с тиснением.",
        keywords: "Нож, сталь шх15, зонная закалка, хамон, 62 hrc, корень ореха, бронза, дерево, деревянная рукоять, кожа, ножны, коричневый, золотой",
    },
    {
        id: '8_08',
        src_1: '/src/assets/products/8_08_01.avif',
        src_2: '/src/assets/products/8_08_02.avif',
        src_3: '/src/assets/products/8_08_03.avif',
        src_4: '/src/assets/products/8_08_04.avif',
        title: "Мини-нож",
        subtitle: "Сталь у8",
        descriptionBlade: "Клинок: сталь у8, зонная закалка, твердость 60 hrc.",
        descriptionHandle: "Рукоять: джинсовая микарта.",
        descriptionScabbard: "",
        filter: "knives-mini",
        alt: "Мини-нож с рукоятью из джинсовой микарты, с заклепкой золотистого цвета.",
        keywords: "Мини-нож, сталь у8, зонная закалка, 60 hrc, джинсовая микарта, кожа, ножны, черный, синий, золотая заклепка",
    },
    {
        id: '8_05',
        src_1: '/src/assets/products/8_05_01.avif',
        src_2: '/src/assets/products/8_05_02.avif',
        src_3: '/src/assets/products/8_05_03.avif',
        src_4: '/src/assets/products/8_05_04.avif',
        src_5: '/src/assets/products/8_05_05.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь у8, зонная закалка, твердость 57 hrc.",
        descriptionHandle: "Рукоять: берёза, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью светло-бежевого неоднородного цвета, ножны темно-бордовые с узорчатым тиснением.",
        keywords: "Нож, сталь у8, зонная закалка, 57 hrc, берёза, бронза, дерево, деревянная рукоять, кожа, ножны, узоры, коричневый, бежевый",
    },
    {
        id: '8_06',
        src_1: '/src/assets/products/8_06_01.avif',
        src_2: '/src/assets/products/8_06_02.avif',
        src_3: '/src/assets/products/8_06_03.avif',
        src_4: '/src/assets/products/8_06_04.avif',
        src_5: '/src/assets/products/8_06_05.avif',
        src_6: '/src/assets/products/8_06_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, булатный узор, твердость 59 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, бронза, проставки.",
        descriptionScabbard: "Ножны: тиснение, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью темного цвета, многоугольной формы.",
        keywords: "Нож, сталь шх15, зонная закалка, булатный узор, 59 hrc, чёрный граб, бронза, дерево, деревянная рукоять, кожа, ножны, коричневый, узоры, геометрический, золотой",
    },
    // ------------------------------------------------------------------------
    {
        id: '7_08',
        src_1: '/src/assets/products/7_08_01.avif',
        src_2: '/src/assets/products/7_08_02.avif',
        src_3: '/src/assets/products/7_08_03.avif',
        src_4: '/src/assets/products/7_08_04.avif',
        src_5: '/src/assets/products/7_08_05.avif',
        src_6: '/src/assets/products/7_08_06.avif',
        src_7: '/src/assets/products/7_08_07.avif',
        src_8: '/src/assets/products/7_08_08.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, твердость 61 hrc.",
        descriptionHandle: "Рукоять: корень ореха, проставки, пропитка, бронза.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью коричневого неоднородного цвета. Ножны темно-красного цвета с узорчатым тиснением.",
        keywords: "Нож, сталь шх15, зонная закалка, 61 hrc, корень ореха, бронза, дерево, деревянная рукоять, ножа, ножны, узоры, коричневый, красный, ореховый, золотой",
    },
    {
        id: '7_09',
        src_1: '/src/assets/products/7_09_01.avif',
        src_2: '/src/assets/products/7_09_02.avif',
        src_3: '/src/assets/products/7_09_03.avif',
        src_4: '/src/assets/products/7_09_04.avif',
        src_5: '/src/assets/products/7_09_05.avif',
        src_6: '/src/assets/products/7_09_06.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, латунь, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью черно-бежевого цвета. Ножны с узорчатым тиснением.",
        keywords: "Нож, сталь У8, зонная закалка, 58 hrc, карельская берёза, бронза, латунь, дерево, деревянная рукоять, кожа, ножны, черный, бежевый, узоры, коричневый, золотой",
    },
    {
        id: '8_07',
        src_1: '/src/assets/products/8_07_01.avif',
        src_2: '/src/assets/products/8_07_02.avif',
        src_3: '/src/assets/products/8_07_03.avif',
        src_4: '/src/assets/products/8_07_04.avif',
        src_5: '/src/assets/products/8_07_05.avif',
        src_6: '/src/assets/products/8_07_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская береза, мельхиор.",
        descriptionScabbard: "Ножны разборные (съемная петля): пропитка,тиснение.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью светло-коричневого неоднородного цвета, разборные ножны с тиснением.",
        keywords: "Нож, сталь шх15, зонная закалка, хамон, 60 hrc, карельская береза, мельхиор, дерево, деревянная рукоять, кожа, ножны разборные (съемная петля), узоры, светло-коричневый",
    },
    {
        id: '8_04',
        src_1: '/src/assets/products/8_04_01.avif',
        src_2: '/src/assets/products/8_04_02.avif',
        src_3: '/src/assets/products/8_04_03.avif',
        src_4: '/src/assets/products/8_04_04.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамасская сталь у8+шх15, твердость 56 hrc.",
        descriptionHandle: "Рукоять: зебрано, мельхиор, проставки, пропитка.",
        descriptionScabbard: "Ножны разборные (съемная петля): тиснение, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож из дамасской стали, рукоять рыжего цвета с черными полосками.",
        keywords: "Нож, дамасская сталь, дамаск, сталь у8+шх15, 56 hrc, зебрано, мельхиор, дерево, деревянная рукоять, кожа, ножны разборные (съемная петля), тигриный, полоски, коричневый, рыжий",
    },
    {
        id: '6_01',
        src_1: '/src/assets/products/6_01_01.avif',
        src_2: '/src/assets/products/6_01_02.avif',
        src_3: '/src/assets/products/6_01_03.avif',
        src_4: '/src/assets/products/6_01_04.avif',
        src_5: '/src/assets/products/6_01_05.avif',
        title: "Нож",
        subtitle: "Сталь у10",
        descriptionBlade: "Клинок: сталь у10, твердость 57 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью черного цвета. Ножны черные.",
        keywords: "Нож, сталь у10, 57 hrc, чёрный граб, патинированная бронза, дерево, деревянная рукоять, кожа, ножны",
    },
    {
        id: '6_06',
        src_1: '/src/assets/products/6_06_01.avif',
        src_2: '/src/assets/products/6_06_02.avif',
        src_3: '/src/assets/products/6_06_03.avif',
        src_4: '/src/assets/products/6_06_04.avif',
        src_5: '/src/assets/products/6_06_05.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 60 hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью светло-зеленого цвета. На ножнах сделано тиснение в виде ветви с листьями.",
        keywords: "Нож, сталь шх15, зонная закалка, 60 hrc, стабилизированная карельская берёза, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, листья, узоры, зеленый, коричневый",
    },
    {
        id: '6_05',
        src_1: '/src/assets/products/6_05_01.avif',
        src_2: '/src/assets/products/6_05_02.avif',
        src_3: '/src/assets/products/6_05_03.avif',
        src_4: '/src/assets/products/6_05_04.avif',
        src_5: '/src/assets/products/6_05_05.avif',
        src_6: '/src/assets/products/6_05_06.avif',
        src_7: '/src/assets/products/6_05_07.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск ,твердость 62 hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, патинированный мельхиор, проставка фибра, финиш.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional, damask-steel",
        alt: "Нож из дамасской стали, с рукоятью темного неоднородного цвета, анатомической формы. Ножны черного цвета.",
        keywords: "Нож, дамасская сталь, дамаск, 62 hrc, стабилизированная карельская берёза, патинированный мельхиор,дерево, деревянная рукоять, кожа, ножны, анатомическая форма, черный, серый, волнистые узоры",
    },
    {
        id: '6_07',
        src_1: '/src/assets/products/6_07_01.avif',
        src_2: '/src/assets/products/6_07_02.avif',
        src_3: '/src/assets/products/6_07_03.avif',
        src_4: '/src/assets/products/6_07_04.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: орех, чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью коричневого цвета под дерево с черными вставками и красными полосками. Ножны коричневые с красной прошивкой.",
        keywords: "Нож, сталь шх15,зонная закалка, 58 hrc, орех, чёрный граб, патинированная бронза, дерево, деревянная рукоять, кожа, ножны, коричневый, красный, ореховый, темный клинок",
    },
    {
        id: '9_04',
        src_1: '/src/assets/products/9_04_01.avif',
        src_2: '/src/assets/products/9_04_02.avif',
        src_3: '/src/assets/products/9_04_03.avif',
        src_4: '/src/assets/products/9_04_04.avif',
        src_5: '/src/assets/products/9_04_05.avif',
        src_6: '/src/assets/products/9_04_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 60 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Нож с рукоятью темно-коричневого цвета с золотистыми вставками.",
        keywords: "Нож, сталь шх15, зонная закалка, хамон, булатный узор, 60 hrc, дерево, деревянная рукоять, кожа, ножны, коричневый, золотой, черный",
    },
    {
        id: '9_05',
        src_1: '/src/assets/products/9_05_01.avif',
        src_2: '/src/assets/products/9_05_02.avif',
        src_3: '/src/assets/products/9_05_03.avif',
        src_4: '/src/assets/products/9_05_04.avif',
        title: "Нож. Скандинав",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 58 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
        alt: "Скандинавский нож с рукоятью из красного дерева, ножны черного цвета с эмблемой.",
        keywords: "Скандинавский нож, сталь шх15, зонная закалка, хамон, 58 hrc, дерево, деревянная рукоять, кожа, ножны, красный, коричневый, черный",
    },
];

export default products;